### ISSUE TITLE
Travis config and deployment script?

### ISSUE THREAD

**Issue by kevinykuo** [koverholt/auto-deploy-rstudio-connect#4]
Found this repo through https://solutions.rstudio.com/deploy/overview/#github-and-travis-ci -- are we missing content in the repo?

**Comment by koverholt** [comment]
In a [previous version of this repo](https://github.com/koverholt/auto-deploy-rstudio-connect/tree/83257197a64bc9674b788ffcf869f38027409043), I was using the deployment APIs in RSC. Since then, I switched to using the built-in git deployment functionality in RSC 1.7.6+. I will update the README here to reflect that.

If you are looking for an RSC API deployment example, you can find that here: https://github.com/rstudio/connect-api-deploy-shiny
